CREATE TABLE IF NOT EXISTS users (
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE KEY,
  name VARCHAR(63),
  password_hash VARCHAR(64) NOT NULL,
  password_salt VARCHAR(24) NOT NULL,
  is_admin BOOLEAN DEFAULT 0,
);
